In [ ]:
import numpy as np

class ConnectFour:
    def __init__(self):
        self.board = np.zeros((6, 7))  # 7x6 grid
        self.player = 1  # Player 1 starts
        self.game_over = False

    def print_board(self):
        print(np.flip(self.board, 0))  # Flip the board to display it properly

    def drop_piece(self, col):
        for row in range(6):
            if self.board[row][col] == 0:
                self.board[row][col] = self.player
                return

    def is_valid_move(self, col):
        return self.board[5][col] == 0

    def check_win(self):
        # Check for horizontal win
        for row in range(6):
            for col in range(4):
                if self.board[row][col] == self.player and \
                   self.board[row][col+1] == self.player and \
                   self.board[row][col+2] == self.player and \
                   self.board[row][col+3] == self.player:
                    return True

        # Check for vertical win
        for row in range(3):
            for col in range(7):
                if self.board[row][col] == self.player and \
                   self.board[row+1][col] == self.player and \
                   self.board[row+2][col] == self.player and \
                   self.board[row+3][col] == self.player:
                    return True

        # Check for diagonal win (top-left to bottom-right)
        for row in range(3):
            for col in range(4):
                if self.board[row][col] == self.player and \
                   self.board[row+1][col+1] == self.player and \
                   self.board[row+2][col+2] == self.player and \
                   self.board[row+3][col+3] == self.player:
                    return True

        # Check for diagonal win (bottom-left to top-right)
        for row in range(3, 6):
            for col in range(4):
                if self.board[row][col] == self.player and \
                   self.board[row-1][col+1] == self.player and \
                   self.board[row-2][col+2] == self.player and \
                   self.board[row-3][col+3] == self.player:
                    return True

        return False

    def check_draw(self):
        return np.all(self.board != 0)

    def switch_player(self):
        self.player = 2 if self.player == 1 else 1

    def play(self, col):
        if not self.game_over and self.is_valid_move(col):
            self.drop_piece(col)
            if self.check_win():
                self.game_over = True
                print(f"Player {self.player} wins!")
            elif self.check_draw():
                self.game_over = True
                print("It's a draw!")
            else:
                self.switch_player()

    def minimax(self, depth, maximizing_player):
        if depth == 0 or self.game_over:
            if self.check_win():
                if maximizing_player:
                    return -1000000  # Large negative value
                else:
                    return 1000000  # Large positive value
            else:
                return 0

        if maximizing_player:
            max_eval = -np.inf
            for col in range(7):
                if self.is_valid_move(col):
                    self.drop_piece(col)
                    eval = self.minimax(depth - 1, False)
                    max_eval = max(max_eval, eval)
                    self.board[np.where(self.board[:, col] != 0)[0][-1]][col] = 0  # Undo the move
            return max_eval
        else:
            min_eval = np.inf
            for col in range(7):
                if self.is_valid_move(col):
                    self.drop_piece(col)
                    eval = self.minimax(depth - 1, True)
                    min_eval = min(min_eval, eval)
                    self.board[np.where(self.board[:, col] != 0)[0][-1]][col] = 0  # Undo the move
            return min_eval

    def find_best_move(self):
        best_eval = -np.inf
        best_move = None
        for col in range(7):
            if self.is_valid_move(col):
                self.drop_piece(col)
                eval = self.minimax(3, False)  # Adjust the depth according to the complexity you want
                if eval > best_eval:
                    best_eval = eval
                    best_move = col
                self.board[np.where(self.board[:, col] != 0)[0][-1]][col] = 0  # Undo the move
        return best_move

# Example usage:
game = ConnectFour()
while not game.game_over:
    game.print_board()
    if game.player == 1:
        col = int(input("Player 1, enter column (0-6): "))
        game.play(col)
    else:
        col = game.find_best_move()
        game.play(col)
game.print_board()

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
Player 1, enter column (0-6): 1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [2. 1. 0. 0. 0. 0. 0.]]
Player 1, enter column (0-6): 2
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [2. 1. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0.]
 [2. 1. 1. 0. 0. 0. 0.]]
Player 1, enter column (0-6): 3
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0.]
 [2. 1. 1. 1. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0.